{"tags": ["golang", "GAE", "datastore", "Go"], "context": "ERROR    2016-02-28 07:30:52,824 api_server.py:272] Exception while handling service_name: \"datastore_v3\"\nmethod: \"Put\"\nrequest: \"\\n\\320\\001j,j\\023dev~hoge-localr\\025\\013\\022\\021AuthrizationToken\\014r\\032\\010\\007\\032\\011CreatedAt \\000*\\011\\010\\275\\363\\340\\230\\370\\231\\313\\002r\\032\\010\\007\\032\\011UpdatedAt \\000*\\011\\010\\275\\363\\340\\230\\370\\231\\313\\002r\\016\\032\\006UserID \\000*\\002\\010\\001r)\\032\\013AccessToken \\000*\\030\\032\\026XQ5xT1e9RtqjkRdD2laTCgr*\\032\\014RefreshToken \\000*\\030\\032\\026Hy7EIN9XQEiX0q1KtbU_MA\\202\\001\\000\"\nrequest_id: \"CAggbZbuys\"\n\nTraceback (most recent call last):\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 247, in _handle_POST\n    api_response = _execute_request(request).Encode()\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 189, in _execute_request\n    make_request()\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 181, in make_request\n    request_id)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 968, in MakeSyncCall\n    response, request_id)\n  File \"/Users/user1/go_appengine/google/appengine/api/apiproxy_stub.py\", line 131, in MakeSyncCall\n    method(request, response)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_stub_util.py\", line 3217, in _Dynamic_Put\n    transaction, self._trusted, self._app_id)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_stub_util.py\", line 2680, in Put\n    full_key = self._AllocateIds([entity.key()])[0]\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 1470, in _AllocateIds\n    'ScatteredIdCounters')\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 1394, in __AllocateIdsFromBlock\n    next_id = c.fetchone()[0]\nTypeError: 'NoneType' object has no attribute '__getitem__'\n\n\n\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3089\u4e00\u5ea6\u30b5\u30fc\u30d0\u3092\u6b62\u3081\u3066\n\u518d\u5ea6\u3001\nbash\ngoapp serve\n\n\u3057\u307e\u3057\u3087\u3046\u3002\n\u305d\u3057\u305f\u3089\u6cbb\u308b\u306f\u305a\u3067\u3059...\n```\nERROR    2016-02-28 07:30:52,824 api_server.py:272] Exception while handling service_name: \"datastore_v3\"\nmethod: \"Put\"\nrequest: \"\\n\\320\\001j,j\\023dev~hoge-localr\\025\\013\\022\\021AuthrizationToken\\014r\\032\\010\\007\\032\\011CreatedAt \\000*\\011\\010\\275\\363\\340\\230\\370\\231\\313\\002r\\032\\010\\007\\032\\011UpdatedAt \\000*\\011\\010\\275\\363\\340\\230\\370\\231\\313\\002r\\016\\032\\006UserID \\000*\\002\\010\\001r)\\032\\013AccessToken \\000*\\030\\032\\026XQ5xT1e9RtqjkRdD2laTCgr*\\032\\014RefreshToken \\000*\\030\\032\\026Hy7EIN9XQEiX0q1KtbU_MA\\202\\001\\000\"\nrequest_id: \"CAggbZbuys\"\n\nTraceback (most recent call last):\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 247, in _handle_POST\n    api_response = _execute_request(request).Encode()\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 189, in _execute_request\n    make_request()\n  File \"/Users/user1/go_appengine/google/appengine/tools/devappserver2/api_server.py\", line 181, in make_request\n    request_id)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 968, in MakeSyncCall\n    response, request_id)\n  File \"/Users/user1/go_appengine/google/appengine/api/apiproxy_stub.py\", line 131, in MakeSyncCall\n    method(request, response)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_stub_util.py\", line 3217, in _Dynamic_Put\n    transaction, self._trusted, self._app_id)\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_stub_util.py\", line 2680, in Put\n    full_key = self._AllocateIds([entity.key()])[0]\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 1470, in _AllocateIds\n    'ScatteredIdCounters')\n  File \"/Users/user1/go_appengine/google/appengine/datastore/datastore_sqlite_stub.py\", line 1394, in __AllocateIdsFromBlock\n    next_id = c.fetchone()[0]\nTypeError: 'NoneType' object has no attribute '__getitem__'\n\n```\n\n\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3089\u4e00\u5ea6\u30b5\u30fc\u30d0\u3092\u6b62\u3081\u3066\n\u518d\u5ea6\u3001\n```bash\ngoapp serve\n```\n\u3057\u307e\u3057\u3087\u3046\u3002\n\u305d\u3057\u305f\u3089\u6cbb\u308b\u306f\u305a\u3067\u3059...\n"}