{"context": " More than 1 year has passed since last update.1\u9031\u9593\u3050\u3089\u3044\u30cf\u30de\u3063\u305f\u306e\u3067\u4e00\u5fdc\u30e1\u30e2\uff0e\n\u74b0\u5883\u306f\n\nWindows 7 64bit\nPython 2.7\n\n\u4f55\u304c\u304d\u3063\u304b\u3051\u304b\u306f\u308f\u304b\u3089\u306a\u3044\u304c\uff0cscipy.ndimage\u3084scipy.misc\u306a\u3069\u3092\u4f7f\u304a\u3046\u3068\u3059\u308b\u3068\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u8868\u793a\u3055\u308c\u308b\u3088\u3046\u306b\u306a\u3063\u305f\uff0e\n>>> import scipy.misc\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"C:\\Python27\\lib\\site-packages\\scipy\\misc\\__init__.py\", line 49, in <modu\nle>\n    from scipy.special import comb, factorial, factorial2, factorialk\n  File \"C:\\Python27\\lib\\site-packages\\scipy\\special\\__init__.py\", line 601, in <\nmodule>\n    from ._ufuncs import *\nImportError: DLL load failed: \u6307\u5b9a\u3055\u308c\u305f\u30e2\u30b8\u30e5\u30fc\u30eb\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\n\n\u539f\u56e0\u304c\u3055\u3063\u3071\u308a\u308f\u304b\u3089\u306a\u3044\uff0escipy\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u76f4\u3057\u3066\u3082\u30c0\u30e1\uff0e\u9014\u65b9\u306b\u66ae\u308c\u3066\u3044\u305f\u3068\u3053\u308d\uff0c\u4ee5\u4e0b\u306e\u8cea\u554f\u3092\u767a\u898b\uff0e\n\n\"ImportError when importing certain modules from SciPY\"\n\n\nhttp://stackoverflow.com/questions/17480779/importerror-when-importing-certain-modules-from-scipy\n\n\n\n\u3053\u306e\u8cea\u554f\u306e\u56de\u7b54\u306b\u3088\u308b\u3068\u3053\u3053\u304b\u3089numpy\u3092\u66f4\u65b0\u3057\u308d\u3068\u306e\u3053\u3068\uff0e\u66f4\u65b0\u3059\u308b\u3068\u78ba\u304b\u306bscipy\u304c\u52d5\u304f\u3088\u3046\u306b\u306a\u3063\u305f\uff0e\u7d50\u5c40\u539f\u56e0\u304c\u306a\u3093\u3060\u3063\u305f\u306e\u304b\u3088\u304f\u308f\u304b\u3089\u306a\u3044\u304cnumpy\u5074\u306b\u554f\u984c\u304c\u3042\u3063\u305f\u3088\u3046\u3060\uff0e\n1\u9031\u9593\u3050\u3089\u3044\u30cf\u30de\u3063\u305f\u306e\u3067\u4e00\u5fdc\u30e1\u30e2\uff0e\n\n\u74b0\u5883\u306f\n\n* Windows 7 64bit\n* Python 2.7\n\n\u4f55\u304c\u304d\u3063\u304b\u3051\u304b\u306f\u308f\u304b\u3089\u306a\u3044\u304c\uff0c`scipy.ndimage`\u3084`scipy.misc`\u306a\u3069\u3092\u4f7f\u304a\u3046\u3068\u3059\u308b\u3068\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u8868\u793a\u3055\u308c\u308b\u3088\u3046\u306b\u306a\u3063\u305f\uff0e\n\n```\n>>> import scipy.misc\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\n  File \"C:\\Python27\\lib\\site-packages\\scipy\\misc\\__init__.py\", line 49, in <modu\nle>\n    from scipy.special import comb, factorial, factorial2, factorialk\n  File \"C:\\Python27\\lib\\site-packages\\scipy\\special\\__init__.py\", line 601, in <\nmodule>\n    from ._ufuncs import *\nImportError: DLL load failed: \u6307\u5b9a\u3055\u308c\u305f\u30e2\u30b8\u30e5\u30fc\u30eb\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\n```\n\n\u539f\u56e0\u304c\u3055\u3063\u3071\u308a\u308f\u304b\u3089\u306a\u3044\uff0escipy\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u76f4\u3057\u3066\u3082\u30c0\u30e1\uff0e\u9014\u65b9\u306b\u66ae\u308c\u3066\u3044\u305f\u3068\u3053\u308d\uff0c\u4ee5\u4e0b\u306e\u8cea\u554f\u3092\u767a\u898b\uff0e\n\n* \"ImportError when importing certain modules from SciPY\"\n  * http://stackoverflow.com/questions/17480779/importerror-when-importing-certain-modules-from-scipy\n\n\u3053\u306e\u8cea\u554f\u306e\u56de\u7b54\u306b\u3088\u308b\u3068[\u3053\u3053](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy)\u304b\u3089numpy\u3092\u66f4\u65b0\u3057\u308d\u3068\u306e\u3053\u3068\uff0e\u66f4\u65b0\u3059\u308b\u3068\u78ba\u304b\u306bscipy\u304c\u52d5\u304f\u3088\u3046\u306b\u306a\u3063\u305f\uff0e\u7d50\u5c40\u539f\u56e0\u304c\u306a\u3093\u3060\u3063\u305f\u306e\u304b\u3088\u304f\u308f\u304b\u3089\u306a\u3044\u304cnumpy\u5074\u306b\u554f\u984c\u304c\u3042\u3063\u305f\u3088\u3046\u3060\uff0e\n", "tags": ["Python", "scipy", "numpy"]}