{"tags": ["pyenv", "Sierra", "Xcode"], "context": "Sierra\u306b\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u305fMac\u3067\u3001pyenv\u3092\u4f7f\u3063\u3066Python\u306e\u74b0\u5883\u3092\u4f5c\u308d\u3046\u3068\u601d\u3044\u307e\u3057\u305f\u3002\n\u3057\u304b\u3057\n$ pyenv install 3.5.1\n\n\u3068\u6253\u3061\u8fbc\u3093\u3067\u3082\nDownloading Python-3.5.1.tar.xz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz\nInstalling Python-3.5.1...\n\nBUILD FAILED (OS X 10.12 using python-build 20160602)\n\nInspect or clean up the working tree at /var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939\nResults logged to /var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939.log\n\nLast 10 log lines:\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__main__.py\", line 4, in <module>\n    ensurepip._main()\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 209, in _main\n    default_pip=args.default_pip,\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 116, in bootstrap\n    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 40, in _run_pip\n    import pip\nzipimport.ZipImportError: can't decompress data; zlib not available\nmake: *** [install] Error 1\n\n\u3053\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u6587\u304c\u51fa\u3066\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u5931\u6557\u3057\u307e\u3059\u3002\n\u5bfe\u7b56\u3068\u3057\u3066\n$ xcode-select --install\n\n\u3092\u6253\u3061\u8fbc\u307f\u307e\u3059\u3002\n\n\u30dd\u30c3\u30d7\u304c\u7acb\u3061\u4e0a\u304c\u308b\u306e\u3067\u3001Xcode\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6e08\u307f\u306e\u65b9\u306f\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3092\u62bc\u3057\u307e\u3059\u3002\n\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u7d42\u4e86\u5f8c\u306b\u3001\n$ pyenv install 3.5.1\n\n\u3092\u3082\u3046\u4e00\u5ea6\u6253\u3061\u8fbc\u3080\u3068\nDownloading Python-3.5.1.tar.xz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz\nInstalling Python-3.5.1...\nInstalled Python-3.5.1 to /Users/username/.pyenv/versions/3.5.1\n\nusername% pyenv versions\n* system (set by /Users/username/.pyenv/version)\n  3.5.1\n\n\u7121\u4e8b\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u307e\u3057\u305f\u3002\n\u4ed6\u306eENV\u3067\u3082\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u304c\u5931\u6557\u3055\u308c\u3066\u308b\u3088\u3046\u3067\u3057\u305f\u3089\u8a66\u3057\u3066\u307f\u3066\u304f\u3060\u3055\u3044\u3002\nSierra\u306b\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u305fMac\u3067\u3001pyenv\u3092\u4f7f\u3063\u3066Python\u306e\u74b0\u5883\u3092\u4f5c\u308d\u3046\u3068\u601d\u3044\u307e\u3057\u305f\u3002\n\u3057\u304b\u3057\n\n```\n$ pyenv install 3.5.1\n```\n\n\u3068\u6253\u3061\u8fbc\u3093\u3067\u3082\n\n```\nDownloading Python-3.5.1.tar.xz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz\nInstalling Python-3.5.1...\n\nBUILD FAILED (OS X 10.12 using python-build 20160602)\n\nInspect or clean up the working tree at /var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939\nResults logged to /var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939.log\n\nLast 10 log lines:\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__main__.py\", line 4, in <module>\n    ensurepip._main()\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 209, in _main\n    default_pip=args.default_pip,\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 116, in bootstrap\n    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)\n  File \"/private/var/folders/q0/xjdlx15d18l2ljx4_924z5vc0000gn/T/python-build.20160924145129.25939/Python-3.5.1/Lib/ensurepip/__init__.py\", line 40, in _run_pip\n    import pip\nzipimport.ZipImportError: can't decompress data; zlib not available\nmake: *** [install] Error 1\n```\n\n\u3053\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u6587\u304c\u51fa\u3066\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u5931\u6557\u3057\u307e\u3059\u3002\n\n\u5bfe\u7b56\u3068\u3057\u3066\n\n```\n$ xcode-select --install\n```\n\n\u3092\u6253\u3061\u8fbc\u307f\u307e\u3059\u3002\n\n\n\n![xcode.png](https://qiita-image-store.s3.amazonaws.com/0/60014/46de26c8-8851-dd05-fa23-1ba7ddbeebd8.png)\n\n\u30dd\u30c3\u30d7\u304c\u7acb\u3061\u4e0a\u304c\u308b\u306e\u3067\u3001Xcode\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6e08\u307f\u306e\u65b9\u306f\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3092\u62bc\u3057\u307e\u3059\u3002\n\n\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u7d42\u4e86\u5f8c\u306b\u3001\n\n```\n$ pyenv install 3.5.1\n```\n\n\u3092\u3082\u3046\u4e00\u5ea6\u6253\u3061\u8fbc\u3080\u3068\n\n```\nDownloading Python-3.5.1.tar.xz...\n-> https://www.python.org/ftp/python/3.5.1/Python-3.5.1.tar.xz\nInstalling Python-3.5.1...\nInstalled Python-3.5.1 to /Users/username/.pyenv/versions/3.5.1\n\nusername% pyenv versions\n* system (set by /Users/username/.pyenv/version)\n  3.5.1\n```\n\n\u7121\u4e8b\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3067\u304d\u307e\u3057\u305f\u3002\n\u4ed6\u306eENV\u3067\u3082\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u304c\u5931\u6557\u3055\u308c\u3066\u308b\u3088\u3046\u3067\u3057\u305f\u3089\u8a66\u3057\u3066\u307f\u3066\u304f\u3060\u3055\u3044\u3002\n"}