{"tags": ["Jupyter", "docker", "aufs", "overlayfs"], "context": "docker \u3067OverlayFS\u3092\u4f7f\u3063\u3066\u3044\u308b\u74b0\u5883\u3067\u8d77\u3053\u3063\u305f\u8a71\u3067\u3059\u3002\n\u81ea\u5206\u3067\u8abf\u67fb\u3057\u305f\u308f\u3051\u3067\u306f\u306a\u3044\u306e\u3060\u304c\u3001\u8208\u5473\u6df1\u3044\u3053\u3068\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u8a18\u4e8b\u306b\u3057\u3066\u307f\u307e\u3057\u305f\u3002\n\n\u6982\u8981\nxfs \u306e\u4e0a\u306bOverlayFS \u3092\u4f7f\u3063\u3066\u3044\u308b\u3068\u304d\u306b\u3001\ndocker \u3067 jupyter/minimal-notebook \u306e\u6700\u8fd1\u306e\u30d0\u30fc\u30b8\u30e7\u30f3(a249876881d3)\u304c\u8d77\u52d5\u3067\u304d\u306a\u3044\u3053\u3068\u304c\u3042\u3063\u305f\u3002\n\u305d\u306e\u5f8c\u306e\u8abf\u67fb\u3067 ext4 \u306e\u4e0a\u306b OverlayFS \u3067\u3082\u540c\u69d8\u306b\u8d77\u52d5\u304c\u3067\u304d\u306a\u304b\u3063\u305f\ndocker run --rm -ti -u root -v $HOME/work:/home/jovyan/work --name jupyter_test -e NB_UID=10001 jupyter/minimal-notebook:a249876881d3\n\n\nAUFS\u3067\u306f\u3069\u3046\u306a\u306e\u304b\uff1f\n\u4ee5\u524ddocker-machine\u3067\u4f5c\u3063\u305faufs\u74b0\u5883\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u8a66\u3057\u3066\u307f\u308b\u3068\u540c\u69d8\u306e\u30a8\u30e9\u30fc\u304c\u3067\u305f\u3002\n\u8a73\u3057\u304f\u306f\u8abf\u3079\u3066\u3044\u306a\u3044\u304c\u3001\u3042\u308b\u6642\u70b9\u3067\u306eaufs\u306b\u3082\u554f\u984c\u304c\u3042\u308b\u306e\u304b\u3082\u3057\u308c\u306a\u3044\uff08\u3059\u3067\u306b\u6cbb\u3063\u3066\u3044\u308b\u304b\u306a\u3069\u3082\u307e\u3060\u8abf\u67fb\u3057\u3066\u3044\u306a\u3044\uff09\n\n\u7d50\u8ad6\n\nFix permissions when host mounting SSL cert/key \u00b7 jupyter/docker-stacks@b7353bf\n\njupyter/docker-stacks\u4e0a\u306e\u3053\u306e\u30b3\u30df\u30c3\u30c8\u3068OverlayFS\u306e\u7d44\u307f\u5408\u308f\u305b\u304c\u554f\u984c\u3067\u306f\u306a\u3044\u304b\u3068\u8003\u3048\u3066\u3044\u308b\u3002\n\u3068\u3059\u308b\u3068\u3001base-notebook \u306b\u5bfe\u3059\u308b\u3082\u306e\u306a\u306e\u3067\u3001docker \u3067OverlayFS\u3092\u5229\u7528\u3057\u3066\u3044\u308b\u74b0\u5883\u3067\u306f\u3001jupyter\u306e\u4ed6\u306e\u30a4\u30e1\u30fc\u30b8\u3082\u540c\u69d8\u306e\u554f\u984c\u304c\u304a\u3053\u308b\u53ef\u80fd\u6027\u304c\u3042\u308b\u3002\n\n\u56de\u907f\u7b56\n\u4ee5\u4e0b\u306e\u65b9\u6cd5\u3067\u56de\u907f\u3067\u304d\u308b\n\njupyter\u306e\u5c11\u3057\u524d\u306e\u30d0\u30fc\u30b8\u30e7\u30f3(8015c88c4b11)\u3092\u4f7f\u3046\ndocker run \u3059\u308b\u3068\u304d\u306bNB_UID\u3092\u6307\u5b9a\u3057\u306a\u3044\nOverlayFS(aufs) \u3092\u3084\u3081\u3066devicemapper \u306a\u3069\u3001\u4ed6\u306e\u30b0\u30e9\u30d5\u30c9\u30e9\u30a4\u30d0\u306b\u3057\u3066\u307f\u308b\u3002\n\u4ee5\u4e0b\u306e\uff12\u3064\u306e\u30d1\u30c3\u30c1\u3092\u3042\u3066\u308b\n\n\novl: ignore permissions on underlying lookup \u00b7 torvalds/linux@38b78a5\nvfs: add lookup_hash() helper \u00b7 torvalds/linux@3c9fe8c\n\n\n\u30ab\u30fc\u30cd\u30eb\u30924.6.0\u4ee5\u964d\u306b\u3059\u308b\n\n\n(\u4eca\u306e\u3068\u3053\u308d4.5\u7cfb\u30844.4stable\u7cfb\u306b\u306f\u53d6\u308a\u8fbc\u307e\u308c\u3066\u3044\u306a\u3044\u3068\u306e\u3053\u3068)\n\n\n\n\n\u539f\u56e0\nxfs\u3067\u3082\u3001ext4\u3067\u3082\u8d77\u3053\u308b\u3068\u3053\u308d\u304b\u3089\u3001OverlayFS\u306b\u554f\u984c\u304c\u3042\u308b\u3068\u8003\u3048\u3066\u3044\u308b\u3002\n\novl: ignore permissions on underlying lookup \u00b7 torvalds/linux@38b78a5\n\n\n\u30a8\u30e9\u30fc\n\u8d77\u52d5\u3059\u308b\u3068\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30e1\u30c3\u30bb\u30fc\u30b8\u304c\u3067\u308b\u3002\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 501, in get\n    value = obj._trait_values[self.name]\nKeyError: 'runtime_dir'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/bin/jupyter-notebook\", line 6, in <module>\n    sys.exit(main())\n  File \"/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py\", line 267, in launch_instance\n    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py\", line 595, in launch_instance\n    app.initialize(argv)\n  File \"<decorator-gen-7>\", line 2, in initialize\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py\", line 74, in catch_config_error\n    return method(app, *args, **kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py\", line 1058, in initialize\n    self.init_configurables()\n  File \"/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py\", line 838, in init_configurables\n    connection_dir=self.runtime_dir,\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 529, in __get__\n    return self.get(obj, cls)\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 508, in get\n    value = self._validate(obj, dynamic_default())\n  File \"/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py\", line 99, in _runtime_dir_default\n    ensure_dir_exists(rd, mode=0o700)\n  File \"/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py\", line 167, in ensure_dir_exists\n    os.makedirs(path, mode=mode)\n  File \"/opt/conda/lib/python3.5/os.py\", line 241, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime'\n\n\n\u8ffd\u8a182016-06-17 Docker for Mac(beta)\u3067\u3082\u8d77\u304d\u308b\u3088\u3046\u3067\u3059\u3002\n\u81ea\u5206\u3067\u78ba\u8a8d\u3057\u305f\u306e\u3067\u306f\u306a\u3044\u304c\u3001\nDocker for Mac(beta)\u74b0\u5883\u3067\u3082\u304a\u3053\u308b\u3088\u3046\u3067\u3059\u3002\ndocker \u3067OverlayFS\u3092\u4f7f\u3063\u3066\u3044\u308b\u74b0\u5883\u3067\u8d77\u3053\u3063\u305f\u8a71\u3067\u3059\u3002\n\u81ea\u5206\u3067\u8abf\u67fb\u3057\u305f\u308f\u3051\u3067\u306f\u306a\u3044\u306e\u3060\u304c\u3001\u8208\u5473\u6df1\u3044\u3053\u3068\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u8a18\u4e8b\u306b\u3057\u3066\u307f\u307e\u3057\u305f\u3002\n\n# \u6982\u8981\n\nxfs \u306e\u4e0a\u306bOverlayFS \u3092\u4f7f\u3063\u3066\u3044\u308b\u3068\u304d\u306b\u3001\ndocker \u3067 [jupyter/minimal-notebook](https://hub.docker.com/r/jupyter/minimal-notebook/) \u306e\u6700\u8fd1\u306e\u30d0\u30fc\u30b8\u30e7\u30f3(a249876881d3)\u304c\u8d77\u52d5\u3067\u304d\u306a\u3044\u3053\u3068\u304c\u3042\u3063\u305f\u3002\n\n\u305d\u306e\u5f8c\u306e\u8abf\u67fb\u3067 ext4 \u306e\u4e0a\u306b OverlayFS \u3067\u3082\u540c\u69d8\u306b\u8d77\u52d5\u304c\u3067\u304d\u306a\u304b\u3063\u305f\n\n```\ndocker run --rm -ti -u root -v $HOME/work:/home/jovyan/work --name jupyter_test -e NB_UID=10001 jupyter/minimal-notebook:a249876881d3\n```\n\n## AUFS\u3067\u306f\u3069\u3046\u306a\u306e\u304b\uff1f\n\n\u4ee5\u524ddocker-machine\u3067\u4f5c\u3063\u305faufs\u74b0\u5883\u304c\u3042\u3063\u305f\u306e\u3067\u3001\u8a66\u3057\u3066\u307f\u308b\u3068\u540c\u69d8\u306e\u30a8\u30e9\u30fc\u304c\u3067\u305f\u3002\n\u8a73\u3057\u304f\u306f\u8abf\u3079\u3066\u3044\u306a\u3044\u304c\u3001\u3042\u308b\u6642\u70b9\u3067\u306eaufs\u306b\u3082\u554f\u984c\u304c\u3042\u308b\u306e\u304b\u3082\u3057\u308c\u306a\u3044\uff08\u3059\u3067\u306b\u6cbb\u3063\u3066\u3044\u308b\u304b\u306a\u3069\u3082\u307e\u3060\u8abf\u67fb\u3057\u3066\u3044\u306a\u3044\uff09\n\n\n\n# \u7d50\u8ad6\n\n* [Fix permissions when host mounting SSL cert/key \u00b7 jupyter/docker-stacks@b7353bf](https://github.com/jupyter/docker-stacks/commit/b7353bf7596119c9e532d39136a6658d667bc782)\n\njupyter/docker-stacks\u4e0a\u306e\u3053\u306e\u30b3\u30df\u30c3\u30c8\u3068OverlayFS\u306e\u7d44\u307f\u5408\u308f\u305b\u304c\u554f\u984c\u3067\u306f\u306a\u3044\u304b\u3068\u8003\u3048\u3066\u3044\u308b\u3002\n\n\u3068\u3059\u308b\u3068\u3001[base-notebook](https://github.com/jupyter/docker-stacks/tree/master/base-notebook) \u306b\u5bfe\u3059\u308b\u3082\u306e\u306a\u306e\u3067\u3001docker \u3067OverlayFS\u3092\u5229\u7528\u3057\u3066\u3044\u308b\u74b0\u5883\u3067\u306f\u3001jupyter\u306e\u4ed6\u306e\u30a4\u30e1\u30fc\u30b8\u3082\u540c\u69d8\u306e\u554f\u984c\u304c\u304a\u3053\u308b\u53ef\u80fd\u6027\u304c\u3042\u308b\u3002\n\n# \u56de\u907f\u7b56\n\n\u4ee5\u4e0b\u306e\u65b9\u6cd5\u3067\u56de\u907f\u3067\u304d\u308b\n\n- jupyter\u306e\u5c11\u3057\u524d\u306e\u30d0\u30fc\u30b8\u30e7\u30f3(8015c88c4b11)\u3092\u4f7f\u3046\n- docker run \u3059\u308b\u3068\u304d\u306bNB_UID\u3092\u6307\u5b9a\u3057\u306a\u3044\n- OverlayFS(aufs) \u3092\u3084\u3081\u3066devicemapper \u306a\u3069\u3001\u4ed6\u306e\u30b0\u30e9\u30d5\u30c9\u30e9\u30a4\u30d0\u306b\u3057\u3066\u307f\u308b\u3002\n- \u4ee5\u4e0b\u306e\uff12\u3064\u306e\u30d1\u30c3\u30c1\u3092\u3042\u3066\u308b\n - [ovl: ignore permissions on underlying lookup \u00b7 torvalds/linux@38b78a5](https://github.com/torvalds/linux/commit/38b78a5f18584db6fa7441e0f4531b283b0e6725)\n - [vfs: add lookup_hash() helper \u00b7 torvalds/linux@3c9fe8c](https://github.com/torvalds/linux/commit/3c9fe8cdff1b889a059a30d22f130372f2b3885f)\n- \u30ab\u30fc\u30cd\u30eb\u30924.6.0\u4ee5\u964d\u306b\u3059\u308b\n - (\u4eca\u306e\u3068\u3053\u308d4.5\u7cfb\u30844.4stable\u7cfb\u306b\u306f\u53d6\u308a\u8fbc\u307e\u308c\u3066\u3044\u306a\u3044\u3068\u306e\u3053\u3068)\n\n# \u539f\u56e0\n\nxfs\u3067\u3082\u3001ext4\u3067\u3082\u8d77\u3053\u308b\u3068\u3053\u308d\u304b\u3089\u3001OverlayFS\u306b\u554f\u984c\u304c\u3042\u308b\u3068\u8003\u3048\u3066\u3044\u308b\u3002\n\n* [ovl: ignore permissions on underlying lookup \u00b7 torvalds/linux@38b78a5](https://github.com/torvalds/linux/commit/38b78a5f18584db6fa7441e0f4531b283b0e6725)\n\n\n# \u30a8\u30e9\u30fc\n\n\u8d77\u52d5\u3059\u308b\u3068\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30e1\u30c3\u30bb\u30fc\u30b8\u304c\u3067\u308b\u3002\n\n```\nTraceback (most recent call last):\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 501, in get\n    value = obj._trait_values[self.name]\nKeyError: 'runtime_dir'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/bin/jupyter-notebook\", line 6, in <module>\n    sys.exit(main())\n  File \"/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py\", line 267, in launch_instance\n    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py\", line 595, in launch_instance\n    app.initialize(argv)\n  File \"<decorator-gen-7>\", line 2, in initialize\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/config/application.py\", line 74, in catch_config_error\n    return method(app, *args, **kwargs)\n  File \"/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py\", line 1058, in initialize\n    self.init_configurables()\n  File \"/opt/conda/lib/python3.5/site-packages/notebook/notebookapp.py\", line 838, in init_configurables\n    connection_dir=self.runtime_dir,\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 529, in __get__\n    return self.get(obj, cls)\n  File \"/opt/conda/lib/python3.5/site-packages/traitlets/traitlets.py\", line 508, in get\n    value = self._validate(obj, dynamic_default())\n  File \"/opt/conda/lib/python3.5/site-packages/jupyter_core/application.py\", line 99, in _runtime_dir_default\n    ensure_dir_exists(rd, mode=0o700)\n  File \"/opt/conda/lib/python3.5/site-packages/ipython_genutils/path.py\", line 167, in ensure_dir_exists\n    os.makedirs(path, mode=mode)\n  File \"/opt/conda/lib/python3.5/os.py\", line 241, in makedirs\n    mkdir(name, mode)\nPermissionError: [Errno 13] Permission denied: '/home/jovyan/.local/share/jupyter/runtime'\n```\n\n### \u8ffd\u8a182016-06-17 Docker for Mac(beta)\u3067\u3082\u8d77\u304d\u308b\u3088\u3046\u3067\u3059\u3002\n\n\u81ea\u5206\u3067\u78ba\u8a8d\u3057\u305f\u306e\u3067\u306f\u306a\u3044\u304c\u3001\nDocker for Mac(beta)\u74b0\u5883\u3067\u3082\u304a\u3053\u308b\u3088\u3046\u3067\u3059\u3002\n\n"}