{"context": " More than 1 year has passed since last update.\u4f55\u304bmac\u306edefault\u306e\u6587\u5b57\u30a8\u30f3\u30b3\u30fc\u30c9\u304cx-mac-japanese\u306bpython2.6\u304c\u5bfe\u5fdc\u3057\u3066\u306a\u3044\u307d\u3044\u3002\n\u53e9\u3044\u305f\u3089\u3053\u3093\u306a\u30a8\u30e9\u30fc\u51fa\u308b\n$ s3cmd --configure\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please report the following lines to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nProblem: LookupError: unknown encoding: x-mac-japanese\nS3cmd:   1.0.1\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 2007, in <module>\n    main()\n  File \"/usr/local/bin/s3cmd\", line 1889, in main\n    sys.stdout = codecs.getwriter(cfg.encoding)(sys.stdout, \"replace\")\n  File \"/usr/local/opt/pyenv/versions/inblue/lib/python2.6/codecs.py\", line 994, in getwriter\n    return lookup(encoding).streamwriter\nLookupError: unknown encoding: x-mac-japanese\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n    Please report the above lines to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n\u3042\u304f\u307e\u3067\u3082\u305d\u306e\u5834\u3057\u306e\u304e\u306e\u5bfe\u5fdc\u3067\u3059\u306e\u3067\u5f8c\u3005\u81ea\u5206\u3067\u3069\u3046\u306b\u304b\u3057\u3066\u304f\u3060\u3055\u3044\n\u5f37\u5236\u7684\u306b\u76f4\u3057\u3061\u3083\u3063\u305f\n/usr/local/bin/s3cmd line 1889 \u5468\u8fba\n1887     ## Set output and filesystem encoding for printing out filenames.\n1888 +    cfg.encoding = \"UTF-8\"\n1889     sys.stdout = codecs.getwriter(cfg.encoding)(sys.stdout, \"replace\")\n1890     sys.stderr = codecs.getwriter(cfg.encoding)(sys.stderr, \"replace\")\n\npython\u3092\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u76f4\u3059\u306e\u3068\u304b\u8f9b\u3044\u306e\u3067\u3053\u3093\u306a\u89e3\u6c7a\u7b56\u3002\n\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u76f4\u3059\u65b9\u6cd5\u306f\u4e0b\u306eURL\u3068\u304b\u306b\u8f09\u3063\u3066\u307e\u3059\u3002\n\u3082\u3063\u3068\u3044\u3044\u65b9\u6cd5\u3092\u3054\u5b58\u77e5\u306e\u65b9\u304c\u304a\u308a\u307e\u3057\u305f\u3089\u662f\u975e\u6559\u3048\u3066\u4e0b\u3055\u3044\u307e\u305bmm\n\n\u53c2\u8003\n\nPython - Django\u306e LookupError: unknown encoding: x-mac-japanese \u306e\u89e3\u6c7a\u65b9\u6cd5 (Django 1.5\u7248) - Qiita\n\u300cLookupError: unknown encoding: X-MAC-JAPANESE\u306e\u7f60 \u300d\u306e\u4ef6 - Django\u3078\u306e\u7247\u601d\u3044\u65e5\u8a18\n\n\n\u4f55\u304bmac\u306edefault\u306e\u6587\u5b57\u30a8\u30f3\u30b3\u30fc\u30c9\u304cx-mac-japanese\u306bpython2.6\u304c\u5bfe\u5fdc\u3057\u3066\u306a\u3044\u307d\u3044\u3002\n\u53e9\u3044\u305f\u3089\u3053\u3093\u306a\u30a8\u30e9\u30fc\u51fa\u308b\n\n```\n$ s3cmd --configure\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please report the following lines to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nProblem: LookupError: unknown encoding: x-mac-japanese\nS3cmd:   1.0.1\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 2007, in <module>\n    main()\n  File \"/usr/local/bin/s3cmd\", line 1889, in main\n    sys.stdout = codecs.getwriter(cfg.encoding)(sys.stdout, \"replace\")\n  File \"/usr/local/opt/pyenv/versions/inblue/lib/python2.6/codecs.py\", line 994, in getwriter\n    return lookup(encoding).streamwriter\nLookupError: unknown encoding: x-mac-japanese\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n    Please report the above lines to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n```\n\n***\u3042\u304f\u307e\u3067\u3082\u305d\u306e\u5834\u3057\u306e\u304e\u306e\u5bfe\u5fdc\u3067\u3059\u306e\u3067\u5f8c\u3005\u81ea\u5206\u3067\u3069\u3046\u306b\u304b\u3057\u3066\u304f\u3060\u3055\u3044***\n\n\u5f37\u5236\u7684\u306b\u76f4\u3057\u3061\u3083\u3063\u305f\n\n/usr/local/bin/s3cmd line 1889 \u5468\u8fba\n\n```python\n1887     ## Set output and filesystem encoding for printing out filenames.\n1888 +    cfg.encoding = \"UTF-8\"\n1889     sys.stdout = codecs.getwriter(cfg.encoding)(sys.stdout, \"replace\")\n1890     sys.stderr = codecs.getwriter(cfg.encoding)(sys.stderr, \"replace\")\n```\n\npython\u3092\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u76f4\u3059\u306e\u3068\u304b\u8f9b\u3044\u306e\u3067\u3053\u3093\u306a\u89e3\u6c7a\u7b56\u3002\n\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u76f4\u3059\u65b9\u6cd5\u306f\u4e0b\u306eURL\u3068\u304b\u306b\u8f09\u3063\u3066\u307e\u3059\u3002\n\n\u3082\u3063\u3068\u3044\u3044\u65b9\u6cd5\u3092\u3054\u5b58\u77e5\u306e\u65b9\u304c\u304a\u308a\u307e\u3057\u305f\u3089\u662f\u975e\u6559\u3048\u3066\u4e0b\u3055\u3044\u307e\u305bmm\n\n### \u53c2\u8003\n\n* [Python - Django\u306e LookupError: unknown encoding: x-mac-japanese \u306e\u89e3\u6c7a\u65b9\u6cd5 (Django 1.5\u7248) - Qiita](http://qiita.com/hagino3000/items/54e7bdbbfa5e99216d04)\n* [\u300cLookupError: unknown encoding: X-MAC-JAPANESE\u306e\u7f60 \u300d\u306e\u4ef6 - Django\u3078\u306e\u7247\u601d\u3044\u65e5\u8a18](http://d.hatena.ne.jp/jYoshiori/20070907/1189184174)\n", "tags": ["s3cmd", "Python", "OSX"]}