{"context": " More than 1 year has passed since last update.\n\n\u6982\u8981\n\u8868\u984c\u306e\u901a\u308a\u3067\u3001Ubuntu\u3092\u30d0\u30fc\u30b8\u30e7\u30f3\u30a2\u30c3\u30d7\u3059\u308b\u524d\u307e\u3067\u306f\u666e\u901a\u306b\u52d5\u3044\u3066\u3044\u305fvirtualenv\u3067\u3001\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3059\u308b\u3088\u3046\u306b\u306a\u308a\u307e\u3057\u305f\n\n$ python -c \"import io\"\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/usr/lib/python2.7/io.py\", line 51, in <module>\n    import _io\nImportError: No module named _io\n\n\n\u89e3\u6c7a\u7b56\nStackOverFlow\u7b49\u3092\u8abf\u3079\u3066\u307f\u308b\u3068virtualenv\u3092\u4f5c\u6210\u3057\u306a\u304a\u3059(requirements.txt\u3092\u4f5c\u3063\u3066\u304a\u3044\u3066\u3001\u524a\u9664\uff06\u518d\u4f5c\u6210\u5f8c\u306b\u518d\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3059\u308b)\u65b9\u6cd5\u304c\u4e00\u822c\u7684\u306a\u89e3\u6c7a\u7b56\u306e\u3088\u3046\u3060\u3063\u305f\u306e\u3067\u3059\u304c\u3001\n\u73fe\u72b6\u306evirtualenv\u304c\u53e4\u3081\u306e\u30d1\u30c3\u30b1\u30fc\u30b8\u3092URL\u6307\u5b9a\u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u305f\u308a\u3057\u3066\u518d\u4f5c\u6210\u304c\u9762\u5012\u3060\u3063\u305f\u306e\u3067\u3001\u4ee5\u4e0b\u306e\u65b9\u6cd5\u3092\u53d6\u308a\u307e\u3057\u305f\u3002\n1.\u9069\u5f53\u306avirtualenv\u3092\u65b0\u3057\u304f\u4f5c\u6210\u3059\u308b\n2.\u7834\u640d\u3057\u305fvirtualenv\u306ebin/python\u3092\u524a\u9664(\u5ff5\u306e\u70ba\u30d0\u30c3\u30af\u30a2\u30c3\u30d7\u3092\u304a\u52e7\u3081\u3057\u307e\u3059)\n3.1\u3067\u4f5c\u6210\u3057\u305fvirtualenv\u306ebin/python\u30922\u306b\u30b3\u30d4\u30fc\n\u4f59\u308a\u3088\u308d\u3057\u3044\u65b9\u6cd5\u3067\u306f\u306a\u3044\u3067\u3059\u304c\u3001\u4e00\u5148\u305a\u3053\u308c\u3067\u73fe\u72b6\u306f\u3057\u306e\u3052\u305f\u306e\u3067\u3057\u3070\u3089\u304f\u69d8\u5b50\u3092\u898b\u308b\u3064\u3082\u308a\u3067\u3059\n\u203b\u305d\u3082\u305d\u3082virtualenvwrapper\u306b\u6642\u4ee3\u9045\u308c\u611f\u304c\u3042\u308b\u306e\u3067\u3001\u3053\u308c\u3092\u6a5f\u306bpyenv\u7b49\u306e\u5c0e\u5165\u3082\u3042\u308a\u3067\u3059\u306d\u2026\n\n\u95a2\u9023URL\nhttp://stackoverflow.com/questions/23176697/importerror-no-module-named-io-in-ubuntu-14-04\n# \u6982\u8981\n\u8868\u984c\u306e\u901a\u308a\u3067\u3001Ubuntu\u3092\u30d0\u30fc\u30b8\u30e7\u30f3\u30a2\u30c3\u30d7\u3059\u308b\u524d\u307e\u3067\u306f\u666e\u901a\u306b\u52d5\u3044\u3066\u3044\u305fvirtualenv\u3067\u3001\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3059\u308b\u3088\u3046\u306b\u306a\u308a\u307e\u3057\u305f\n\n```shell-session\n\n$ python -c \"import io\"\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/usr/lib/python2.7/io.py\", line 51, in <module>\n    import _io\nImportError: No module named _io\n```\n\n\n# \u89e3\u6c7a\u7b56\nStackOverFlow\u7b49\u3092\u8abf\u3079\u3066\u307f\u308b\u3068virtualenv\u3092\u4f5c\u6210\u3057\u306a\u304a\u3059(requirements.txt\u3092\u4f5c\u3063\u3066\u304a\u3044\u3066\u3001\u524a\u9664\uff06\u518d\u4f5c\u6210\u5f8c\u306b\u518d\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3059\u308b)\u65b9\u6cd5\u304c\u4e00\u822c\u7684\u306a\u89e3\u6c7a\u7b56\u306e\u3088\u3046\u3060\u3063\u305f\u306e\u3067\u3059\u304c\u3001\n\u73fe\u72b6\u306evirtualenv\u304c\u53e4\u3081\u306e\u30d1\u30c3\u30b1\u30fc\u30b8\u3092URL\u6307\u5b9a\u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u305f\u308a\u3057\u3066\u518d\u4f5c\u6210\u304c\u9762\u5012\u3060\u3063\u305f\u306e\u3067\u3001\u4ee5\u4e0b\u306e\u65b9\u6cd5\u3092\u53d6\u308a\u307e\u3057\u305f\u3002\n\n1.\u9069\u5f53\u306avirtualenv\u3092\u65b0\u3057\u304f\u4f5c\u6210\u3059\u308b\n2.\u7834\u640d\u3057\u305fvirtualenv\u306ebin/python\u3092\u524a\u9664(\u5ff5\u306e\u70ba\u30d0\u30c3\u30af\u30a2\u30c3\u30d7\u3092\u304a\u52e7\u3081\u3057\u307e\u3059)\n3.1\u3067\u4f5c\u6210\u3057\u305fvirtualenv\u306ebin/python\u30922\u306b\u30b3\u30d4\u30fc\n\n\u4f59\u308a\u3088\u308d\u3057\u3044\u65b9\u6cd5\u3067\u306f\u306a\u3044\u3067\u3059\u304c\u3001\u4e00\u5148\u305a\u3053\u308c\u3067\u73fe\u72b6\u306f\u3057\u306e\u3052\u305f\u306e\u3067\u3057\u3070\u3089\u304f\u69d8\u5b50\u3092\u898b\u308b\u3064\u3082\u308a\u3067\u3059\n\u203b\u305d\u3082\u305d\u3082virtualenvwrapper\u306b\u6642\u4ee3\u9045\u308c\u611f\u304c\u3042\u308b\u306e\u3067\u3001\u3053\u308c\u3092\u6a5f\u306bpyenv\u7b49\u306e\u5c0e\u5165\u3082\u3042\u308a\u3067\u3059\u306d\u2026\n\n# \u95a2\u9023URL\nhttp://stackoverflow.com/questions/23176697/importerror-no-module-named-io-in-ubuntu-14-04\n", "tags": ["Ubuntu12.04", "Ubuntu14.04", "python2.7"]}