{"context": " More than 1 year has passed since last update.\n\n\u53c2\u8003\n\nosx - Selenium and Python on Snow Leopard - Stack Overflow\n\nFirefox\u304c /Applications\u306b\u306a\u3044\u3068\u30a8\u30e9\u30fc\u306b\u306a\u308b\u3002\n\u81ea\u5206\u306f$HOME/app/\u306a\u3069HOME\u30c7\u30a3\u30ec\u30af\u30c8\u30ea\u306b\u7f6e\u304f\u3053\u3068\u304c\u591a\u3044\u306e\u3067\u906d\u9047\u3057\u305f\u3002\n\n\u30a8\u30e9\u30fc\u4f8b\n$ python mrtg.py\nE\n======================================================================\nERROR: test_c3 (__main__.C3)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"mrtg.py\", line 12, in setUp\n    self.driver = webdriver.Firefox()\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py\", line 64, in __init__\n    self.binary, timeout),\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 51, in __init__\n    self.binary.launch_browser(self.profile)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 69, in launch_browser\n    self._start_from_profile_path(self.profile.path)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 92, in _start_from_profile_path\n    env=self._firefox_env)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 709, in __init__\n    errread, errwrite)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 1326, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n\n----------------------------------------------------------------------\nRan 1 test in 0.228s\n\nFAILED (errors=1)\n\n\n## \u53c2\u8003\n\n* [osx - Selenium and Python on Snow Leopard - Stack Overflow](http://stackoverflow.com/questions/8334706/selenium-and-python-on-snow-leopard)\n\nFirefox\u304c `/Applications`\u306b\u306a\u3044\u3068\u30a8\u30e9\u30fc\u306b\u306a\u308b\u3002\n\u81ea\u5206\u306f`$HOME/app/`\u306a\u3069HOME\u30c7\u30a3\u30ec\u30af\u30c8\u30ea\u306b\u7f6e\u304f\u3053\u3068\u304c\u591a\u3044\u306e\u3067\u906d\u9047\u3057\u305f\u3002\n\n## \u30a8\u30e9\u30fc\u4f8b\n\n```bash:\n$ python mrtg.py\nE\n======================================================================\nERROR: test_c3 (__main__.C3)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"mrtg.py\", line 12, in setUp\n    self.driver = webdriver.Firefox()\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/webdriver.py\", line 64, in __init__\n    self.binary, timeout),\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/extension_connection.py\", line 51, in __init__\n    self.binary.launch_browser(self.profile)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 69, in launch_browser\n    self._start_from_profile_path(self.profile.path)\n  File \"/Library/Python/2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py\", line 92, in _start_from_profile_path\n    env=self._firefox_env)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 709, in __init__\n    errread, errwrite)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py\", line 1326, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n\n----------------------------------------------------------------------\nRan 1 test in 0.228s\n\nFAILED (errors=1)\n```\n", "tags": ["Selenium"]}