{"context": " More than 1 year has passed since last update.\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u307e\u3059\u3002\n------------------------------------------------------------\n/usr/bin/pip3 run on Mon Aug 24 16:16:43 2015\nException:\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/basecommand.py\", line 122, in main\n    status = self.run(options, args)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 80, in run\n    self.run_listing(options)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 142, in run_listing\n    self.output_package_listing(installed_packages)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 151, in output_package_listing\n    if dist_is_editable(dist):\n  File \"/usr/lib/python3/dist-packages/pip/util.py\", line 367, in dist_is_editable\n    req = FrozenRequirement.from_dist(dist, [])\n  File \"/usr/lib/python3/dist-packages/pip/__init__.py\", line 299, in from_dist\n    assert len(specs) == 1 and specs[0][0] == '=='\nAssertionError\n\n\u8b0e\u3063\u307d\u3044\u3002\nGitHub \u306b issue \u304c\u3042\u3063\u305f\u306e\u3067\u3001\u305d\u308c\u306b\u5f93\u3063\u3066pip3 install -U distribute\u3057\u3066\u307f\u305f\u3051\u3069\u3001\u76f4\u3089\u305a\u3002\n\n\u5bfe\u51e6\u6cd5\n\u4ed5\u65b9\u306a\u3044\u306e\u3067 apt-get \u3057\u305f pip \u3092\u524a\u9664\u3057\u3066easy_install3 pip\u3057\u305f\u3089\u76f4\u308a\u307e\u3057\u305f\u3002\n\u8b0e\u3063\u307d\u3044\u3002\n\u3053\u3093\u306a\u30a8\u30e9\u30fc\u304c\u51fa\u307e\u3059\u3002\n\n```\n------------------------------------------------------------\n/usr/bin/pip3 run on Mon Aug 24 16:16:43 2015\nException:\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/basecommand.py\", line 122, in main\n    status = self.run(options, args)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 80, in run\n    self.run_listing(options)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 142, in run_listing\n    self.output_package_listing(installed_packages)\n  File \"/usr/lib/python3/dist-packages/pip/commands/list.py\", line 151, in output_package_listing\n    if dist_is_editable(dist):\n  File \"/usr/lib/python3/dist-packages/pip/util.py\", line 367, in dist_is_editable\n    req = FrozenRequirement.from_dist(dist, [])\n  File \"/usr/lib/python3/dist-packages/pip/__init__.py\", line 299, in from_dist\n    assert len(specs) == 1 and specs[0][0] == '=='\nAssertionError\n```\n\n\u8b0e\u3063\u307d\u3044\u3002\n[GitHub \u306b issue \u304c\u3042\u3063\u305f](https://github.com/pypa/pip/issues/1093)\u306e\u3067\u3001\u305d\u308c\u306b\u5f93\u3063\u3066`pip3 install -U distribute`\u3057\u3066\u307f\u305f\u3051\u3069\u3001\u76f4\u3089\u305a\u3002\n\n## \u5bfe\u51e6\u6cd5\n\u4ed5\u65b9\u306a\u3044\u306e\u3067 apt-get \u3057\u305f pip \u3092\u524a\u9664\u3057\u3066`easy_install3 pip`\u3057\u305f\u3089\u76f4\u308a\u307e\u3057\u305f\u3002\n\u8b0e\u3063\u307d\u3044\u3002\n", "tags": ["Ubuntu", "python3", "pip"]}