{"context": "Mezzanine\u3092\u306f\u3058\u3081\u3088\u3046\u3068\u3044\u3046\u8a18\u4e8b\u3092\u53c2\u8003\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3088\u3046\u3068\u3057\u3066\u3044\u308b\u306e\u3060\u3051\u308c\u3069\u3082\u30a8\u30e9\u30fc\u7d9a\u304d\u3067\u4e0a\u624b\u304f\u5165\u3063\u3066\u304f\u308c\u306a\u3044\u3002\npip3 install mezzanine\u3092\u884c\u3046\u3068\u3001\nCollecting mezzanine\n  Downloading Mezzanine-4.2.2-py2.py3-none-any.whl (6.1MB)\n    96% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258a | 5.8MB 134kB/s eta 0:00:02Exception:\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 232, in _error_catcher\n    yield\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 314, in read\n    data = self._fp.read(amt)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py\", line 60, in read\n    data = self.__fp.read(amt)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 929, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 791, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 575, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/commands/install.py\", line 324, in run\n    requirement_set.prepare_files(finder)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 357, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 324, in read\n    flush_decoder = True\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py\", line 77, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 237, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n\n\u3068\u3044\u3046\u30a8\u30e9\u30fc\u30ed\u30b0\u304c\u51fa\u3066\u6765\u308b\u3002\u3069\u3046\u3084\u3089\uff12\u500b\u3081\u306e\u30a8\u30e9\u30fcraise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\u306f\u3069\u3046\u3084\u3089reuqests\u304burllib3\u5468\u8fba\u304c\u539f\u56e0\u304b\u306a\u3068\u601d\u3063\u305f\u306e\u3067reuqests\u3092\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u3066\u307f\u308b\u3002\npip3 install --upgrade requests\n\u518d\u5ea6\u884c\u3063\u3066\u3082\u540c\u3058\u30a8\u30e9\u30fc\u304c\u51fa\u308b\u3002\nCollecting mezzanine\n  Downloading Mezzanine-4.2.2-py2.py3-none-any.whl (6.1MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 6.1MB 76kB/s\nCollecting pillow (from mezzanine)\n  Downloading Pillow-4.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)\n    84% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588     | 2.9MB 242kB/s eta 0:00:03Exception:\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 232, in _error_catcher\n    yield\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 314, in read\n    data = self._fp.read(amt)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py\", line 60, in read\n    data = self.__fp.read(amt)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 929, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 791, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 575, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/commands/install.py\", line 324, in run\n    requirement_set.prepare_files(finder)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 357, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 324, in read\n    flush_decoder = True\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py\", line 77, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 237, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n\n\u3068\u3044\u3046\u3053\u3068\u3067pip3 install urllib3\u3092\u884c\u306a\u3046\u3002\nCollecting urllib3\n  Downloading urllib3-1.19.1-py2.py3-none-any.whl (104kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 112kB 2.2MB/s\nInstalling collected packages: urllib3\nSuccessfully installed urllib3-1.19.1\n\n\u3082\u3046\u4e00\u5ea6Mezzanine\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u6311\u6226\uff01\nCollecting mezzanine\n  Using cached Mezzanine-4.2.2-py2.py3-none-any.whl\nCollecting requests-oauthlib>=0.4 (from mezzanine)\n  Downloading requests_oauthlib-0.7.0-py2.py3-none-any.whl\nCollecting tzlocal>=1.0 (from mezzanine)\n  Downloading tzlocal-1.3.tar.gz\nCollecting beautifulsoup4>=4.1.3 (from mezzanine)\n  Downloading beautifulsoup4-4.5.3-py3-none-any.whl (85kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 92kB 2.3MB/s\nCollecting pillow (from mezzanine)\n  Downloading Pillow-4.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 3.4MB 181kB/s\nRequirement already satisfied: django<1.11,>=1.8 in ./venv_ryugakuotaku/lib/python3.5/site-packages (from mezzanine)\nCollecting filebrowser-safe>=0.4.6 (from mezzanine)\n  Downloading filebrowser_safe-0.4.6-py2.py3-none-any.whl (218kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 225kB 1.1MB/s\nCollecting django-contrib-comments (from mezzanine)\n  Downloading django_contrib_comments-1.7.3-py2.py3-none-any.whl (406kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 409kB 1.1MB/s\nCollecting bleach>=1.4 (from mezzanine)\n  Downloading bleach-1.5.0-py2.py3-none-any.whl\nCollecting future>=0.9.0 (from mezzanine)\n  Downloading future-0.16.0.tar.gz (824kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 829kB 572kB/s\nCollecting chardet (from mezzanine)\n  Downloading chardet-2.3.0.tar.gz (164kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 174kB 1.8MB/s\nRequirement already satisfied: requests>=2.1.0 in ./venv_ryugakuotaku/lib/python3.5/site-packages (from mezzanine)\nCollecting grappelli-safe>=0.4.5 (from mezzanine)\n  Downloading grappelli_safe-0.4.5-py2.py3-none-any.whl (158kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 163kB 1.3MB/s\nCollecting oauthlib>=0.6.2 (from requests-oauthlib>=0.4->mezzanine)\n  Downloading oauthlib-2.0.1.tar.gz (122kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 133kB 1.7MB/s\nCollecting pytz (from tzlocal>=1.0->mezzanine)\n  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 491kB 1.0MB/s\nCollecting olefile (from pillow->mezzanine)\n  Downloading olefile-0.43.zip (119kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 122kB 2.6MB/s\nCollecting six (from bleach>=1.4->mezzanine)\n  Downloading six-1.10.0-py2.py3-none-any.whl\nCollecting html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 (from bleach>=1.4->mezzanine)\n  Downloading html5lib-0.9999999.tar.gz (889kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 890kB 629kB/s\nInstalling collected packages: oauthlib, requests-oauthlib, pytz, tzlocal, beautifulsoup4, olefile, pillow, filebrowser-safe, django-contrib-comments, six, html5lib, bleach, future, chardet, grappelli-safe, mezzanine\n  Running setup.py install for oauthlib ... done\n  Running setup.py install for tzlocal ... done\n  Running setup.py install for olefile ... done\n  Running setup.py install for html5lib ... done\n  Running setup.py install for future ... done\n  Running setup.py install for chardet ... done\nSuccessfully installed beautifulsoup4-4.5.3 bleach-1.5.0 chardet-2.3.0 django-contrib-comments-1.7.3 filebrowser-safe-0.4.6 future-0.16.0 grappelli-safe-0.4.5 html5lib-0.9999999 mezzanine-4.2.2 oauthlib-2.0.1 olefile-0.43 pillow-4.0.0 pytz-2016.10 requests-oauthlib-0.7.0 six-1.10.0 tzlocal-1.3\n\n\u51fa\u6765\u305f\uff01\n<a href=\"http://qiita.com/itkr/items/c6c26f55a292f3e39241\" target=\"_blank\">Mezzanine\u3092\u306f\u3058\u3081\u3088\u3046</a>\u3068\u3044\u3046\u8a18\u4e8b\u3092\u53c2\u8003\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3088\u3046\u3068\u3057\u3066\u3044\u308b\u306e\u3060\u3051\u308c\u3069\u3082\u30a8\u30e9\u30fc\u7d9a\u304d\u3067\u4e0a\u624b\u304f\u5165\u3063\u3066\u304f\u308c\u306a\u3044\u3002\n\n`pip3 install mezzanine`\u3092\u884c\u3046\u3068\u3001\n\n```\nCollecting mezzanine\n  Downloading Mezzanine-4.2.2-py2.py3-none-any.whl (6.1MB)\n    96% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u258a | 5.8MB 134kB/s eta 0:00:02Exception:\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 232, in _error_catcher\n    yield\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 314, in read\n    data = self._fp.read(amt)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py\", line 60, in read\n    data = self.__fp.read(amt)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 929, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 791, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 575, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/commands/install.py\", line 324, in run\n    requirement_set.prepare_files(finder)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 357, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 324, in read\n    flush_decoder = True\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py\", line 77, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 237, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n```\n\n\u3068\u3044\u3046\u30a8\u30e9\u30fc\u30ed\u30b0\u304c\u51fa\u3066\u6765\u308b\u3002\u3069\u3046\u3084\u3089\uff12\u500b\u3081\u306e\u30a8\u30e9\u30fc`raise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.`\u306f\u3069\u3046\u3084\u3089`reuqests`\u304b`urllib3`\u5468\u8fba\u304c\u539f\u56e0\u304b\u306a\u3068\u601d\u3063\u305f\u306e\u3067`reuqests`\u3092\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3057\u3066\u307f\u308b\u3002\n\n`pip3 install --upgrade requests`\n\n\u518d\u5ea6\u884c\u3063\u3066\u3082\u540c\u3058\u30a8\u30e9\u30fc\u304c\u51fa\u308b\u3002\n\n```\nCollecting mezzanine\n  Downloading Mezzanine-4.2.2-py2.py3-none-any.whl (6.1MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 6.1MB 76kB/s\nCollecting pillow (from mezzanine)\n  Downloading Pillow-4.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)\n    84% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588     | 2.9MB 242kB/s eta 0:00:03Exception:\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 232, in _error_catcher\n    yield\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 314, in read\n    data = self._fp.read(amt)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/cachecontrol/filewrapper.py\", line 60, in read\n    data = self.__fp.read(amt)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 448, in read\n    n = self.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py\", line 488, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 929, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 791, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py\", line 575, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/basecommand.py\", line 215, in main\n    status = self.run(options, args)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/commands/install.py\", line 324, in run\n    requirement_set.prepare_files(finder)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 380, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/req/req_set.py\", line 620, in _prepare_file\n    session=self.session, hashes=hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 821, in unpack_url\n    hashes=hashes\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 659, in unpack_http_url\n    hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 882, in _download_http_url\n    _download_url(resp, link, content_file, hashes)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 603, in _download_url\n    hashes.check_against_chunks(downloaded_chunks)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/hashes.py\", line 46, in check_against_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 571, in written_chunks\n    for chunk in chunks:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/utils/ui.py\", line 139, in iter\n    for x in it:\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/download.py\", line 560, in resp_read\n    decode_content=False):\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 357, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 324, in read\n    flush_decoder = True\n  File \"/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py\", line 77, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/Users/hironorisama/Projects/github/ryugakuotaku/venv_ryugakuotaku/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py\", line 237, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\npip._vendor.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out.\n```\n\n\u3068\u3044\u3046\u3053\u3068\u3067`pip3 install urllib3`\u3092\u884c\u306a\u3046\u3002\n\n```\nCollecting urllib3\n  Downloading urllib3-1.19.1-py2.py3-none-any.whl (104kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 112kB 2.2MB/s\nInstalling collected packages: urllib3\nSuccessfully installed urllib3-1.19.1\n```\n\n\u3082\u3046\u4e00\u5ea6Mezzanine\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u6311\u6226\uff01\n\n```\nCollecting mezzanine\n  Using cached Mezzanine-4.2.2-py2.py3-none-any.whl\nCollecting requests-oauthlib>=0.4 (from mezzanine)\n  Downloading requests_oauthlib-0.7.0-py2.py3-none-any.whl\nCollecting tzlocal>=1.0 (from mezzanine)\n  Downloading tzlocal-1.3.tar.gz\nCollecting beautifulsoup4>=4.1.3 (from mezzanine)\n  Downloading beautifulsoup4-4.5.3-py3-none-any.whl (85kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 92kB 2.3MB/s\nCollecting pillow (from mezzanine)\n  Downloading Pillow-4.0.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.4MB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 3.4MB 181kB/s\nRequirement already satisfied: django<1.11,>=1.8 in ./venv_ryugakuotaku/lib/python3.5/site-packages (from mezzanine)\nCollecting filebrowser-safe>=0.4.6 (from mezzanine)\n  Downloading filebrowser_safe-0.4.6-py2.py3-none-any.whl (218kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 225kB 1.1MB/s\nCollecting django-contrib-comments (from mezzanine)\n  Downloading django_contrib_comments-1.7.3-py2.py3-none-any.whl (406kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 409kB 1.1MB/s\nCollecting bleach>=1.4 (from mezzanine)\n  Downloading bleach-1.5.0-py2.py3-none-any.whl\nCollecting future>=0.9.0 (from mezzanine)\n  Downloading future-0.16.0.tar.gz (824kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 829kB 572kB/s\nCollecting chardet (from mezzanine)\n  Downloading chardet-2.3.0.tar.gz (164kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 174kB 1.8MB/s\nRequirement already satisfied: requests>=2.1.0 in ./venv_ryugakuotaku/lib/python3.5/site-packages (from mezzanine)\nCollecting grappelli-safe>=0.4.5 (from mezzanine)\n  Downloading grappelli_safe-0.4.5-py2.py3-none-any.whl (158kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 163kB 1.3MB/s\nCollecting oauthlib>=0.6.2 (from requests-oauthlib>=0.4->mezzanine)\n  Downloading oauthlib-2.0.1.tar.gz (122kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 133kB 1.7MB/s\nCollecting pytz (from tzlocal>=1.0->mezzanine)\n  Downloading pytz-2016.10-py2.py3-none-any.whl (483kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 491kB 1.0MB/s\nCollecting olefile (from pillow->mezzanine)\n  Downloading olefile-0.43.zip (119kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 122kB 2.6MB/s\nCollecting six (from bleach>=1.4->mezzanine)\n  Downloading six-1.10.0-py2.py3-none-any.whl\nCollecting html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 (from bleach>=1.4->mezzanine)\n  Downloading html5lib-0.9999999.tar.gz (889kB)\n    100% |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 890kB 629kB/s\nInstalling collected packages: oauthlib, requests-oauthlib, pytz, tzlocal, beautifulsoup4, olefile, pillow, filebrowser-safe, django-contrib-comments, six, html5lib, bleach, future, chardet, grappelli-safe, mezzanine\n  Running setup.py install for oauthlib ... done\n  Running setup.py install for tzlocal ... done\n  Running setup.py install for olefile ... done\n  Running setup.py install for html5lib ... done\n  Running setup.py install for future ... done\n  Running setup.py install for chardet ... done\nSuccessfully installed beautifulsoup4-4.5.3 bleach-1.5.0 chardet-2.3.0 django-contrib-comments-1.7.3 filebrowser-safe-0.4.6 future-0.16.0 grappelli-safe-0.4.5 html5lib-0.9999999 mezzanine-4.2.2 oauthlib-2.0.1 olefile-0.43 pillow-4.0.0 pytz-2016.10 requests-oauthlib-0.7.0 six-1.10.0 tzlocal-1.3\n```\n\n\u51fa\u6765\u305f\uff01\n", "tags": ["Django", "Mezzanine"]}