{"context": "Ubunbu(16.04)\u4e0a\u3067\u3001\u3054\u304f\u5358\u7d14\u306astd::call_once\u3092\u547c\u3076\u30b3\u30fc\u30c9\u3092\u30b3\u30f3\u30d1\u30a4\u30eb\u30fb\u30ea\u30f3\u30af\u3057\u3066\u5b9f\u884c\u3059\u308b\u3068\u3001\n#include <mutex>\n#include <iostream>\n\nint main(void) {\n    std::once_flag flag;\n    std::call_once(flag, []() {\n        std::cout << \"hello world\\n\";\n    });\n}\n\n$ g++ -std=c++11 a.cpp\n$ ./a.out \nterminate called after throwing an instance of 'std::system_error'\n  what():  Unknown error -1\nAborted (core dumped)\n\n\u306a\u305c\u304b\u5b9f\u884c\u6642\u306b\u4f8b\u5916\u304c\u6295\u3052\u3089\u308c\u307e\u3059\u3002\u3057\u304b\u3057-pthread\u3092\u4ed8\u3051\u308b\u3068\u3001\n$ g++ -std=c++11 a.cpp -pthread\n$ ./a.out \nhello world\n\n\u4e0a\u624b\u304f\u52d5\u304d\u307e\u3059\u3002MacOS\u3067\u306f-pthread\u306a\u3057\u3067\u3082\u554f\u984c\u3042\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002\n\u53c2\u8003\uff1a\nhttp://stackoverflow.com/questions/15311469/throwing-an-exception-from-stdcall-once\nhttps://gcc.gnu.org/bugzilla/show_bug.cgi?id=60662\nhttps://gcc.gnu.org/bugzilla/show_bug.cgi?id=58929\nUbunbu(16.04)\u4e0a\u3067\u3001\u3054\u304f\u5358\u7d14\u306a`std::call_once`\u3092\u547c\u3076\u30b3\u30fc\u30c9\u3092\u30b3\u30f3\u30d1\u30a4\u30eb\u30fb\u30ea\u30f3\u30af\u3057\u3066\u5b9f\u884c\u3059\u308b\u3068\u3001\n\n```cpp\n#include <mutex>\n#include <iostream>\n\nint main(void) {\n    std::once_flag flag;\n    std::call_once(flag, []() {\n        std::cout << \"hello world\\n\";\n    });\n}\n```\n\n```bash\n$ g++ -std=c++11 a.cpp\n$ ./a.out \nterminate called after throwing an instance of 'std::system_error'\n  what():  Unknown error -1\nAborted (core dumped)\n```\n\n\u306a\u305c\u304b\u5b9f\u884c\u6642\u306b\u4f8b\u5916\u304c\u6295\u3052\u3089\u308c\u307e\u3059\u3002\u3057\u304b\u3057`-pthread`\u3092\u4ed8\u3051\u308b\u3068\u3001\n\n```bash\n$ g++ -std=c++11 a.cpp -pthread\n$ ./a.out \nhello world\n```\n\n\u4e0a\u624b\u304f\u52d5\u304d\u307e\u3059\u3002MacOS\u3067\u306f`-pthread`\u306a\u3057\u3067\u3082\u554f\u984c\u3042\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002\n\n\u53c2\u8003\uff1a\nhttp://stackoverflow.com/questions/15311469/throwing-an-exception-from-stdcall-once\nhttps://gcc.gnu.org/bugzilla/show_bug.cgi?id=60662\nhttps://gcc.gnu.org/bugzilla/show_bug.cgi?id=58929\n\n", "tags": ["C++", "C++11"]}