{"context": " More than 1 year has passed since last update.\n\nencoding:utf8\nfrom Tkinter import *\nimport tkFileDialog as dialog\ndef save(root, text):\n    data = text.get('0.0', END)\n    filename = dialog.asksaveasfilename(\n        parent = root,\n        filetypes=[('Text', '*.txt')],\n        title='\u540d\u524d\u3092\u4ed8\u3051\u3066\u4fdd\u5b58...')\n    writer = open(filename, 'w')\n    writer.write(data.encode('utf8'))\n    writer.close()\ndef quit(root):\n    root.destroy()\nwindow = Tk()\ntext = Text(window)\ntext.pack()\nmenubar = Menu(window)\nfilemenu = Menu(menubar)\nfilemenu.add_command(label='\u4fdd\u5b58', command=lambda : save(window, text))\nfilemenu.add_command(label='\u7d42\u4e86', command=lambda : quit(window))\nmenubar.add_cascade(label='\u30d5\u30a1\u30a4\u30eb', menu=filemenu)\nwindow.config(menu=menubar)\nwindow.mainloop()\n'''\nException in Tkinter callback\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/lib-tk/Tkinter.py\", line 1413, in call\n    return self.func(*args)\n  File \"menu.py\", line 23, in \n    filemenu.add_command(label='Save', command=lambda : save(window, text))\n  File \"menu.py\", line 11, in save\n    writer.write(data)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)\n'''\n'''\n    \u521d\u3081\u3066\u306e\u30b3\u30f3\u30d4\u30e5\u30fc\u30bf\u30b5\u30a4\u30a8\u30f3\u30b9 gui/menu.py\u3088\u308a\u305d\u306e\u307e\u307e\u3060\u3068\u30a8\u30e9\u30fc\u3060\u3063\u305f\u306e\u3067\n    writer.write(data)\u3067\u306f\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u306e\u3067\n    writer,write(data.encode('utf8')\u3068\u3001data.encode('utf8')\u3092\u8ffd\u52a0\u3057\u3066\u307f\u305f\u3002\n'''\n#encoding:utf8\n\nfrom Tkinter import *\nimport tkFileDialog as dialog\n\ndef save(root, text):\n    data = text.get('0.0', END)\n    filename = dialog.asksaveasfilename(\n        parent = root,\n        filetypes=[('Text', '*.txt')],\n        title='\u540d\u524d\u3092\u4ed8\u3051\u3066\u4fdd\u5b58...')\n    writer = open(filename, 'w')\n    writer.write(data.encode('utf8'))\n    writer.close()\n    \ndef quit(root):\n    root.destroy()\n        \nwindow = Tk()\ntext = Text(window)\ntext.pack()\n    \nmenubar = Menu(window)\nfilemenu = Menu(menubar)\nfilemenu.add_command(label='\u4fdd\u5b58', command=lambda : save(window, text))\nfilemenu.add_command(label='\u7d42\u4e86', command=lambda : quit(window))\n    \nmenubar.add_cascade(label='\u30d5\u30a1\u30a4\u30eb', menu=filemenu)\nwindow.config(menu=menubar)\n    \nwindow.mainloop()\n\n\n'''\nException in Tkinter callback\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/lib-tk/Tkinter.py\", line 1413, in __call__\n    return self.func(*args)\n  File \"menu.py\", line 23, in <lambda>\n    filemenu.add_command(label='Save', command=lambda : save(window, text))\n  File \"menu.py\", line 11, in save\n    writer.write(data)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)\n\n'''\n\n'''\n    \u521d\u3081\u3066\u306e\u30b3\u30f3\u30d4\u30e5\u30fc\u30bf\u30b5\u30a4\u30a8\u30f3\u30b9 gui/menu.py\u3088\u308a\u305d\u306e\u307e\u307e\u3060\u3068\u30a8\u30e9\u30fc\u3060\u3063\u305f\u306e\u3067\n    writer.write(data)\u3067\u306f\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u306e\u3067\n    writer,write(data.encode('utf8')\u3068\u3001data.encode('utf8')\u3092\u8ffd\u52a0\u3057\u3066\u307f\u305f\u3002\n'''", "tags": ["Python", "Beginner"]}